version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-aurory}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aurory}
      POSTGRES_DB: ${POSTGRES_DB:-aurory}
    ports: ['5432:5432']
    volumes: [pgdata:/var/lib/postgresql/data]

  mongo:
    image: mongo:7
    ports: ['27017:27017']
    volumes: [mongodata:/data/db]

  redis:
    image: redis:7
    ports: ['6379:6379']

volumes:
  pgdata:
  mongodata:
